### PR TITLE
deps: update various deps

### PR DESCRIPTION
**Pull request by ckipp01**
The main reason for this is to update the nimbus-jose-jwt dep which has a critical vulnerability attached to it which is causing issues at $work. This also replaces some deprecated methods.

### CODE REVIEW

**Review by guizmaii — APPROVED** [review]

**Comment by guizmaii** [comment]
Thanks @ckipp01!
I'm happily surprised anybody is still using this lib :)

**Comment by guizmaii** [comment]
Hum. Tests fail. Can you have a look? I'll try to have a look a bit later today if you didn't do it meanwhile

**Comment by ckipp01** [comment]
> Hum. Tests fail. Can you have a look? I'll try to have a look a bit later today if you didn't do it meanwhile

Ahhh so I solved this for 2.13 but not for 2.12. I can utilize

```
@nowarn("msg=discarded non-Unit value")
```
To ignore it for Scala 2.12, but then I end up with

```
@nowarn annotation does not suppress any warnings
```
for 2.13. Do you want to still support 2.12 or do you know any tricks to just suppress the warnings (which turn into errors) in the spec files?

**Comment by ckipp01** [comment]
> I'm happily surprised anybody is still using this lib :)

Ha, of course. It has worked well for us, and it _if it aint broke, don't touch it_. So we'll continue to use it if we can get the vulnerabilities gone ha.

**Comment by guizmaii** [comment]
@ckipp01 I'm all for removing Scala 2.12 support :)

**Comment by guizmaii** [comment]
@ckipp01 It's releasing https://github.com/guizmaii/scala-nimbus-jose-jwt/actions/runs/10053105364

**Comment by guizmaii** [comment]
And it failed. Of course. Let me fix that

**Comment by guizmaii** [comment]
@ckipp01 It's really publishing this time: https://github.com/guizmaii-opensource/scala-nimbus-jose-jwt/actions/runs/10053281091/job/27785796296

**Pull request merged**
